# Dockerfile to install the latest version of RoonServer for Linux x86_64
FROM debian:bullseye

# Install prerequisite packages
RUN apt-get update \
	&& apt-get install -y --no-install-recommends curl bzip2 ffmpeg cifs-utils libasound2 libicu67 ca-certificates \
	&& apt-get clean && apt-get autoclean
